export const PUBLIC_LANGUAGE = "PUBLIC_LANGUAGE";
export const PUBLIC_UNITY = "PUBLIC_UNITY";
export const PUBLIC_CAMERA_STATE = "PUBLIC_CAMERA_STATE";
export const PUBLIC_PAGE_DATA = "PUBLIC_PAGE_DATA";
export const PUBLIC_CURRENT_PAGE = "PUBLIC_CURRENT_PAGE";
export const PUBLIC_PREVIOUS_PAGE = "PUBLIC_PREVIOUS_PAGE";
export const PUBLIC_LOADING = "PUBLIC_LOADING";
/* ---------- 模型清單 ---------- */
export const DATA_MODEL_READ = "DATA_MODEL_READ";
export const DATA_MODEL_DELETE = "DATA_MODEL_DELETE";
export const DATA_MODEL_CHOSEN = "DATA_MODEL_CHOSEN";
/* ---------- 標點清單 ---------- */
export const DATA_POINT_READ = "DATA_POINT_READ";
export const DATA_POINT_DELETE = "DATA_POINT_DELETE";
export const DATA_POINT_CHOSEN = "DATA_POINT_CHOSEN";
/* ---------- 路徑清單 ---------- */
export const DATA_PATH_READ = "DATA_PATH_READ";
export const DATA_PATH_DELETE = "DATA_PATH_DELETE";
export const DATA_PATH_CHOSEN = "DATA_PATH_CHOSEN";
/* ---------- 加工清單 ---------- */
export const DATA_WORKING_READ = "DATA_WORKING_READ";
export const DATA_WORKING_DELETE = "DATA_WORKING_DELETE";
export const DATA_WORKING_CHOSEN = "DATA_WORKING_CHOSEN";
export const DATA_WORKING_UPDATE = "DATA_WORKING_UPDATE";
export const DATA_WORKING_CREATE = "DATA_WORKING_CREATE";
export const DATA_EQUITMENT_READ_DEFAULT = "DATA_EQUITMENT_READ_DEFAULT";

export const DATA_EQUITMENT_READ = "DATA_EQUITMENT_READ";
/* 中央控制 */
export const DATA_CENTER_CONTROL_READ = "DATA_CENTER_CONTROL_READ";
/* 異常日誌 */
export const DATA_ABNORMAL_LOG_READ = "DATA_ABNORMAL_LOG_READ";
